# Generated by Django 4.1.3 on 2023-01-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company',
         '0020_delete_exist_company_remove_company_confirm_password_and_more'),
        ('baseuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('website', models.URLField()),
                ('number_of_employees', models.IntegerField()),
                ('organization_type',
                 models.CharField(choices=[('pub', 'Public'),
                                           ('pri', 'Private'),
                                           ('sel', 'Self-Employed'),
                                           ('oth', 'Other')], max_length=3)),
                ('revenue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='tinyurl.com/2a382vsm',
                                              upload_to='profile_images')),
                ('about', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='baseusers',
            name='password',
        ),
        migrations.AddField(
            model_name='baseusers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='baseusers',
            name='password1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baseusers',
            name='password2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baseusers',
            name='user_type',
            field=models.CharField(choices=[('per', 'Person'), ('com',
                                                                'Company')],
                                   default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseusers',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='baseusers',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_user',
            field=models.OneToOneField(on_delete=django.db.models.
                                       deletion.CASCADE,
                                       related_name='profile',
                                       to='baseuser.baseusers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='current_company',
                                    to='company.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_companies',
            field=models.ManyToManyField(blank=True,
                                         related_name='past_companies',
                                         to='company.company'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='base_user',
            field=models.OneToOneField(on_delete=django.db.models.
                                       deletion.CASCADE,
                                       related_name='company_profile',
                                       to='baseuser.baseusers'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.
                                       deletion.SET_NULL,
                                       related_name='company_user',
                                       to='company.company'),
        ),
    ]
