# Generated by Django 4.1.3 on 2022-11-28 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseuser', '0002_taskuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='django_user',
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='taskuser',
                to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
