# Generated by Django 4.1.3 on 2023-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0004_remove_baseusers_password_baseusers_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
