# Generated by Django 4.1.3 on 2023-01-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0005_rename_profile_userprofile_baseusers_user_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='type',
            new_name='organization_type',
        ),
    ]
