# Generated by Django 4.1.3 on 2023-01-15 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_template_question_alter_survey_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseuser', '0005_alter_profile_past_companies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseUsers',
            new_name='BaseUser',
        ),
    ]
