# Generated by Django 4.1.3 on 2023-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0006_rename_baseusers_baseuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
