# Generated by Django 4.1.3 on 2023-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser',
         '0007_alter_baseusers_email_alter_companyprofile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_images/default.jpg',
                                    upload_to='profile_images'),
        ),
    ]
