# Generated by Django 4.1.3 on 2023-01-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0005_search'),
        ('baseuser', '0007_alter_baseusers_email_alter_companyprofile_company_and_more'),
    ]

    operations = [
    ]
