# Generated by Django 4.1.3 on 2023-01-17 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_delete_exist_company_remove_company_confirm_password_and_more'),
        ('baseuser', '0007_baseusers_companyprofile_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0006_alter_submission_submitter_alter_survey_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='baseuser.baseusers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_companies',
            field=models.ManyToManyField(blank=True, related_name='past_companies', to='company.company'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='base_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='baseuser.baseusers'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user', to='company.company'),
        ),
        migrations.AddField(
            model_name='baseusers',
            name='django_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
