# Generated by Django 4.1.3 on 2023-01-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0008_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True,
                                    default='profile_images/default.jpg',
                                    null=True, upload_to='profile_images'),
        ),
    ]
