# Generated by Django 4.1.3 on 2023-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0008_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusers',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
