# Generated by Django 4.1.3 on 2023-01-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0009_baseusers_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusers',
            name='is_company',
        ),
    ]
