# Generated by Django 4.1.3 on 2023-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0010_remove_baseusers_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusers',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='baseusers',
            name='password2',
        ),
        migrations.AddField(
            model_name='baseusers',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseusers',
            name='email',
            field=models.EmailField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseusers',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
