# Generated by Django 4.1.3 on 2022-12-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('salary', models.CharField(max_length=20)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
            ],
        ),
    ]
