# Generated by Django 4.1.3 on 2022-12-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_jobdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('salary', models.CharField(max_length=20)),
                ('company_name',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='company',
                                   to='company.company')),
            ],
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
