# Generated by Django 4.1.3 on 2023-01-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_basecompany_alter_jobposting_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecompany',
            name='address',
        ),
        migrations.RemoveField(
            model_name='basecompany',
            name='email',
        ),
        migrations.RemoveField(
            model_name='basecompany',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='basecompany',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
