# Generated by Django 4.1.3 on 2023-01-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_name_basecompany_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecompany',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='basecompany',
            name='legal_papers',
        ),
    ]
