# Generated by Django 4.1.3 on 2023-01-12 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_remove_basecompany_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecompany',
            name='user',
        ),
        migrations.AddField(
            model_name='basecompany',
            name='django_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BaseCompany', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
