# Generated by Django 4.1.3 on 2023-01-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_basecompany_django_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecompany',
            old_name='name',
            new_name='company_name',
        ),
    ]
