# Generated by Django 4.1.3 on 2023-01-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_name_basecompany_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecompany',
            old_name='django_user',
            new_name='user',
        ),
    ]
