# Generated by Django 4.1.3 on 2023-01-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
