# Generated by Django 4.1.3 on 2023-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_company_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exist_Company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='django_user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
