# Generated by Django 4.1.3 on 2022-11-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='question_id',
            new_name='question',
        ),
    ]
