# Generated by Django 4.1.3 on 2022-11-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('company', '0001_initial'),
        ('survey', '0002_alter_answerchoice_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseuser.baseusers'),
            preserve_default=False,
        ),
    ]
