# Generated by Django 4.1.3 on 2023-01-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0004_remove_baseusers_password_baseusers_date_created_and_more'),
        ('survey', '0003_alter_submission_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseuser.baseusers'),
        ),
    ]
