# Generated by Django 4.1.3 on 2023-01-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_jobposting_company_name_jobposting_company'),
        ('survey', '0005_question_template_question_alter_survey_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company'),
        ),
    ]
