# Generated by Django 4.1.3 on 2023-01-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0007_baseusers_companyprofile_userprofile_and_more'),
        ('survey', '0005_question_template_question_alter_survey_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseuser.baseusers'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseuser.baseusers'),
        ),
    ]
