name: CI

on:
  push:
    on: [push, pull_request] #triggers the actions on pushing to any branch and on any pull request

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    services:
      postgres:
        image: postgres:latest
        env: # change those using ${{ secrets.VARIABLE NAME on production }}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install coverage
          python -m pip install flake8
      - name: Coding Style
        run: |
          flake8 --exclude venv,manage.py

      - name: Run migrations
        env:
          EMAIL_HOST_USER: 'ADD YOUR HOST_USER'
          EMAIL_HOST_PASSWORD: 'ADD_YOUR_PASSWORD'
        run: python manage.py migrate
      - name: Run tests
        env:
          EMAIL_HOST_USER: 'ADD YOUR HOST_USER'
          EMAIL_HOST_PASSWORD: 'ADD_YOUR_PASSWORD'
        run: python manage.py test
      - name: Coverage
        env:
          EMAIL_HOST_USER: 'ADD YOUR HOST_USER'
          EMAIL_HOST_PASSWORD: 'ADD_YOUR_PASSWORD'
        run: |
          coverage run --source . manage.py test
          coverage report --fail-under 60